IMAGE_ubuntu_2204   = "bento/ubuntu-22.04"

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_ubuntu_2204
  config.vm.hostname = "server"
  config.vm.provider "virtualbox" do |my_vm|
    my_vm.name = "vagrant_vm"
    my_vm.memory = 2048
    my_vm.cpus = 2
  end
  config.vm.provision :shell, path: "bootstrap.sh"
end